'use client';
/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */

import '@/styles/globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import Nav from '@/component/Home_Component/Nav';
import Footer from '@/component/Home_Component/Footer';
import TopButton from '@/component/Home_Component/TopButton';

import { AnimatePresence } from 'framer-motion';
import { RecoilRoot } from 'recoil';
import { Analytics } from '@vercel/analytics/react';
import { QueryClient, QueryClientProvider } from 'react-query';
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <title>키클 에듀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/kikle_edu_logo_512.png" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,400,0,0"
        />
      </head>
      <body>
        <StyledComponentsRegistry>
          <QueryClientProvider client={queryClient}>
            <RecoilRoot>
              <AnimatePresence mode="wait">
                <Nav />
                {children}
                <Analytics />
                <TopButton />
                <Footer />
              </AnimatePresence>
            </RecoilRoot>
          </QueryClientProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
