/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */
/* eslint-disable @next/next/no-sync-scripts */
import '@/styles/globals.css';
import Head from 'next/head';
import Nav from '@/component/Home_Component/Nav';
import Footer from '@/component/Home_Component/Footer';
import TopButton from '@/component/Home_Component/TopButton';
import NavMobileSideMenuTouchHandler from '@/handler/NavMobileSideMenuTouchHandler'; // NavMobile SideMeue Open Trigger

// import Page from '@/component/Motion_Paging/Page'; // 모든 페이지 이동 시 적용되는 페이지 애니메이션
import { AnimatePresence } from 'framer-motion';

import { Analytics } from '@vercel/analytics/react';
import { RecoilRoot } from 'recoil';

import { QueryClient, QueryClientProvider } from 'react-query';
const queryClient = new QueryClient();

import { appWithTranslation } from 'next-i18next';

function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>키클 에듀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/kikle_edu_logo_512.png" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,400,0,0"
        />
      </Head>
      <QueryClientProvider client={queryClient}>
        <RecoilRoot>
          <AnimatePresence mode="wait">
            <Nav />
            <NavMobileSideMenuTouchHandler />
            <Component {...pageProps} />
            <Analytics />
            <TopButton />
            <Footer />
          </AnimatePresence>
        </RecoilRoot>
      </QueryClientProvider>
    </>
  );
}

export default appWithTranslation(App);
